# Generated by Django 3.1.7 on 2021-03-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=250)),
                ('ingridients', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
