# Generated by Django 3.1.7 on 2021-03-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipeapp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
